# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-26 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0023_auto_20190508_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='days_of_emchilgee',
            old_name='is_done',
            new_name='is_done_aternoon',
        ),
        migrations.AddField(
            model_name='days_of_emchilgee',
            name='is_done_evening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='days_of_emchilgee',
            name='is_done_morning',
            field=models.BooleanField(default=False),
        ),
    ]
